name: flutter_starting_app
description: This is a good starting point for any new project. Comes already with must-have packages and services for a mobile app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  auth_api:
    path: packages/auth_api
  bloc: ^8.1.0
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.1.0
  graphql_api:
    path: packages/graphql_api
  intl: ^0.17.0
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
